# Generated by Django 3.1.4 on 2021-01-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0002_auto_20210104_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
