# Generated by Django 3.1.4 on 2021-01-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0004_auto_20210104_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='send_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
